mpi:
  - nompi
  - mpich
  - openmpi
# This is to make sure "mpi" above is *NOT* used to compute the package hash. For "cutensornet"
# the non-colliding hashes are acceptable (though not preferred if avoidable) because we
# wanted 3 flavors of "cutensornet" generated. But, for the "cuquantum" metapackage if the
# hashes are not colliding we'd also generate 3 packages (one for each "mpi" flavor), despite
# it has nothing to do with MPI. We better make sure we have colliding hashes, so that only
# 1 unique upload would be done by the CI.
ignore_version:
  - mpi


arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]

# conda-forge only supports cross-compiling with CUDA 11.2

cuda_compiler:
  - nvcc

docker_image:                                  # [os.environ.get("BUILD_PLATFORM", "").startswith("linux")]
   - quay.io/condaforge/linux-anvil-cuda:11.2  # [(aarch64 or ppc64le) and os.environ.get("BUILD_PLATFORM") == "linux-64"]

c_compiler_version:        # [linux]
  - 10                     # [aarch64 or ppc64le]

cxx_compiler_version:      # [linux]
  - 10                     # [aarch64 or ppc64le]

fortran_compiler_version:  # [linux]
  - 10                     # [aarch64 or ppc64le]

cuda_compiler_version:
  - 11.2                   # [aarch64 or ppc64le]

cudnn:
  - 8                      # [aarch64 or ppc64le]

cdt_name:  # [linux]
  - cos7   # [aarch64 or ppc64le]
